### ISSUE TITLE
Personal Config data in a separate file

### ISSUE THREAD

**Issue by DarkAllMan** [Egregius/PHP-Floorplan-and-advanced-automation-for-Domoticz#1]
I suggest to put all configurable personal data like:
- domoticz server address
- Kodi clients
- Telegram Token/ChatID
- Lat/Long
- Weatherapp credentials etc
in a separate file like:
.\config\config.inc.php

**Comment by Egregius** [comment]
You can put all of them in secure/settings.php.
I like the url's hardcoded because they hardly ever change.
Some personal variables are on the top of the files because their only needed in that page or script.

**Comment by Egregius** [comment]
I've added a config file outside the site in /var/www/config.php
That one stores the different private variables.
And added an example config file in secure folder
